//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ПР6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Pokupki
    {
        public int idPokupka { get; set; }
        public System.DateTime date { get; set; }
        public int idTovar { get; set; }
        public int idSotr { get; set; }
        public double kol { get; set; }
        public double count { get; set; }
        public double stoimost { get; set; }
    
        public virtual Table_Sotrudniki Table_Sotrudniki { get; set; }
        public virtual Table_Tovari Table_Tovari { get; set; }
    }
}
