//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ПР6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Sotrudniki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Sotrudniki()
        {
            this.Photos = new HashSet<Photos>();
            this.Table_Pokupki = new HashSet<Table_Pokupki>();
        }
    
        public int idSotr { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string otchestvo { get; set; }
        public int idGender { get; set; }
        public System.DateTime birthday { get; set; }
        public string login { get; set; }
        public int password { get; set; }
        public int idRole { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photos> Photos { get; set; }
        public virtual Table_Genders Table_Genders { get; set; }
        public virtual Table_Pasporta Table_Pasporta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Pokupki> Table_Pokupki { get; set; }
        public virtual Table_Roles Table_Roles { get; set; }
    }
}
